### PR TITLE
Getting shallow data instead of nested data

### PR DESCRIPTION
**Pull request by bcolthurst**
I had been looking for a way to just get shallow results (i.e. not the eagerly loaded results that contain nested children objects), and the only way I could figure out to do it was to add a "shallow" flag in the list and read controllers that, if true, skips the includes.
Thought this might be useful to others.

### CODE REVIEW

**Comment by tommybananas** [comment]
It looks good to me, let me look into these node 8 test failures and then we'll also want to add documentation to the readme. Thanks for this

**Comment by tommybananas** [comment]
Can you try merging master? I think the build is failing and a fix is on master. thanks!

**Comment by bcolthurst** [comment]
Hey -- thanks so much -- I just merged master from finale, removed console logs, added some comment documentation, added 2 sections to the readme.  LMK if I need to do anything to update the PR, but I think those commits I made to my fork master are showing up here.

**Comment by shamoons** [comment]
Any updates on this?

**Comment by bcolthurst** [comment]
@shamoons hey -- I just merged in the latest tommybananas/finale into my fork and did a number of things.  Should have kept it cleaner, but here's what I've done:

- merged latest master into my fork
- added a Dockerfile for running tests (I found that getting Dtrace to work on my mac didn't go so well, but in a docker container Dtrace works fine)
- upgraded a lot of libraries to try and get rid of npm package high severity warnings.
- Tried out sequelize 5.x but it has a fatal flaw in how it deals with underscored: true, which broke a ton of tests. So reverted to latest 4.x sequelize
- Got the tests passing.

I don't think it's ready for prime-time just yet --- not sure if everyone else wants to upgrade the various dependencies or not.

But I hope to write some tests specific to the "shallow" read/list feature and an "add_to_all" context feature that lets you inject attributes on creation.

**Comment by tommybananas** [comment]
If you can write those tests and get cleaned up I will merge this. I'm going to work on upgrading the dependencies in the meantime.

**Comment by tommybananas** [comment]
I just fixed the high severity dependencies. If you could merge in the lastest from master and get everything cleaned up, I'll merge this PR. Thanks!

**Comment by bcolthurst** [comment]
Hey @tommybananas  -- I just added tests for the context.shallow and 'children' query param for selecting which associations to include.  Also merged in latest from tommybananas/finale master branch.  Had to fix up a dependency on node 5 I errantly introduced.  The only thing missing IMHO right now are tests for the context.add_to_all feature I added on the create action.  Will work on that now.

**Comment by bcolthurst** [comment]
Just added in add_to_children functionality, tests, and readme documentation.  It's limited to 1-level of nesting -- it doesn't recursively decorate nested objects.  This limitation is included in the documentation.

**Comment by tommybananas** [comment]
Nice work thanks, merged

**Comment by bcolthurst** [comment]
Nice!  Thanks so much!

**Pull request merged**
